### ISSUE TITLE
Analyse CSS without any HTML page

### ISSUE THREAD

**Issue by gnclmorais** [oyvindeh/ucss#33]
I think it would be helpful to be able to run the tool without having to provide any page, just CSS files.

**Comment by jogjayr** [comment]
@gnclmorais did you find an alternative to ucss for getting identifying duplicate CSS?

**Comment by gnclmorais** [comment]
Nah, nothing reliable or that I regularly use.

**Comment by oyvindeh** [comment]
Sorry about not working on this. I'll look into it as soon as possible.

**Comment by jogjayr** [comment]
@oyvindeh Thanks, no need to rush though. I managed to work around it by creating a blank HTML with just a reference to my CSS file and it works great for finding duplicates.

**Comment by astrotim** [comment]
+1 for this feature. This is my exact my use case.

**Comment by joeytwiddle** [comment]
[stylelint](https://stylelint.io/) can find duplicate selectors, amongst other things.
