### ISSUE TITLE
Whether an array is empty or not should be judged by its length, not its self.

### ISSUE THREAD

**Issue by reorx** [oyvindeh/ucss#40]
In `lib/helpers/output.js`, line 128:

https://github.com/oyvindeh/ucss/blob/master/lib/helpers/output.js#L128

```
            if (result.load_errors) {
                console.log("\n" + RED + BOLD + "WARNING: " + RESET
                            + "Some resources were not loaded successfully. This "
                            + "affects the result. Please see crawler log for "
                            + "more information.");
            }
```

this should be `if (result.load_errors.length) {`, otherwise it will always be true.

**Comment by ideadapt** [comment]
Hello!

 

New message, please read <http://nicheinsurance.com.au/spent.php?nfq>

 

kunz@ideadapt.net
