### ISSUE TITLE
Wildcard in middle of exclude URL doesn't work

### ISSUE THREAD

**Issue by svivian** [oyvindeh/ucss#45]
Example config:

	module.exports = {
		pages: {
			crawl: "http://example.com/",
			exclude: [
				"http://example.com/*/list",
			],
		},

		css: [
			"http://example.com/styles.css",
		],
	};

When I run ucss it still fetches URLs like `http://example.com/thing/list`

By extension this also means patterns with multiple wildcards - e.g. `http://example.com/*/list/*` - do not work either.

**Comment by oyvindeh** [comment]
Hey! Wildcard in the middle of a path won't work. But you can use a RegEx to do the same thing. 

First, upgrade to uCSS 0.5.0, then try replacing
```
exclude: [
  "http://example.com/*/list",
],
```
with
```
exclude: [
  http:\/\/example.com\/.+\/list
],
```
Hopefully that should work! :)

**Comment by svivian** [comment]
OK thanks, will do.
