### ISSUE TITLE
offtop: Do you know tool for converting obsolete html attributes to styles?

### ISSUE THREAD

**Issue by a-x-** [oyvindeh/ucss#48]
I want to perform complex old-school HTML modernization 
`uncss` solves part of my issue, but maybe you know other tools I want.

Thank you

**Comment by oyvindeh** [comment]
Hi! I cannot point you to any specific tools. I think I would have made a list of tasks, and then search for tools that does those specific things. Also, perhaps AWK and SED could be useful if you're going to edit a large amount of files based on patterns.

**Comment by a-x-** [comment]
Thank you. I'm gonna dig deep
