### ISSUE TITLE
How does it find all unused css rules？

### ISSUE THREAD

**Issue by Nnnina** [oyvindeh/ucss#49]
How dose it find all unused css rule? Could it find out if a adjacent sibling combinator is used or not?

**Comment by oyvindeh** [comment]
Sorry about the late reply!

It uses Cheerio* to find elements in the DOM based on a CSS selectors. Adjacent sibling selectors should work, ref. this test: https://github.com/oyvindeh/ucss/blob/450f4a8370851b198598af20ed9a9af4a376e58b/test/selectors.js#L127

* Cheerio is an implementation of jQuery core, for the server: https://www.npmjs.com/package/cheerio
